[package]
authors = ["The Rust Project Developers"]
name = "rust-demangler"
version = "0.0.0"
edition = "2018"

[dependencies]
rustc-demangle = "0.1"

[[bin]]
name = "rust-demangler"
path = "main.rs"
