[package]
name = "fakeptr"
version = "0.1.0"
authors = ["Elijah Rivera <eerivera@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
