[package]
authors = ["The Rust Project Developers"]
name = "rustc_index"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
arrayvec = "0.5.1"
rustc_serialize = { path = "../rustc_serialize" }
rustc_macros = { path = "../rustc_macros" }
